from manimlib.imports import *
class lesson_1(Scene):
    def construct(self):
        title = TextMobject("An overview on Trigonometry")
        title.scale(1)
        self.play(Write(title))
        self.wait(3)
        self.play(FadeOut(title))
        
        '''insert unit circle diagram'''

        
        trig = TextMobject("Trigonon --> Triangle")
        trig2 = TextMobject("Metron --> Measure")
        self.play(Write(trig))
        trig2.move_to(DOWN)
        self.wait()
        self.play(Write(trig2))
        self.wait(3)
        self.play(FadeOut(trig), FadeOut(trig2))
        self.wait(3)
        text2 = TextMobject("Relates angles with sides!")
        self.play(Write(text2))
        self.wait(3)
        self.play(FadeOut(text2))
        
        grid = NumberPlane()
        self.add(grid)
        start = (0,0,0)
        end = (3,3,0)
        arc2 = Arc()
        arclabel = TexMobject("\\theta")
        arclabel.move_to(RIGHT* 0.2 + UP * 0.1)
        arclabel.scale(0.5)
        arc2.scale(0.22)
        arc2.move_to(RIGHT*0.3 + UP * 0.15)
        label1, label2, label3 = TextMobject("A"), TextMobject("B"), TextMobject("C")
        label1.move_to((3, 3.3, 0))
        label2.move_to((3, -0.3, 0))
        label3.move_to((0, -0.3, 0))
        sidelabel = TextMobject('hyp')
        sidelabel2 = TextMobject('opp')
        sidelabel3 = TextMobject('adj')
        sidelabel.move_to((1.5, 1.8, 0))
        sidelabel.rotate(PI/4)
        sidelabel2.move_to((3.6,1.5,0))
        sidelabel3.move_to((1.5,-0.5,0))
        
        line1 = Line(start, end)
        line2 = Line(end, (3,0,0))
        start2 = (3,0.5,0)
        end2 = (2.5,0.5,0)
        end3 = (2.5,0,0)
        line3 = Line(start2, end2)
        line4 = Line(end2, end3)
        self.play(ShowCreation(line1), ShowCreation(line2), ShowCreation(arc2), ShowCreation(arclabel), ShowCreation(line3), ShowCreation(line4))
        self.add(label1, label2, label3, sidelabel, sidelabel2, sidelabel3)
        self.wait(3)
        self.remove(label1, label2, label3, sidelabel, sidelabel2, sidelabel3)
        self.play(FadeOut(line1), FadeOut(line2), FadeOut(arc2), FadeOut(arclabel), FadeOut(line3), FadeOut(line4))
        self.remove(grid)
        self.wait(3)
        f1,f2,f3,f4,f5,f6 = TexMobject("sin \\theta"), TexMobject("cos \\theta"), TexMobject("tan \\theta"), TexMobject("csc \\theta"), TexMobject ("sec \\theta"), TexMobject("cot \\theta")
        f1.move_to(UP*2 + LEFT * 2)
        f2.move_to(LEFT*2)
        f3.move_to(LEFT * 2 + DOWN * 2)
        f4.move_to(UP*2)
        
        f6.move_to (DOWN*2)
        self.play(Write(f1),Write(f2), Write(f3), Write(f4), Write(f5), Write(f6))
        self.wait(3)
        self.play(FadeOut(f1), FadeOut(f2), FadeOut(f3), FadeOut(f4), FadeOut(f5), FadeOut(f6))
        si = TexMobject("sin \\theta = \\frac{opposite}{hypoteneuse}")
        cosayn = TexMobject("cos \\theta = \\frac{adjacent}{hypoteneuse}")
        tan = TexMobject("tan \\theta = \\frac{opposite}{adjacent}")
        csc = TexMobject("csc \\theta = \\frac{1}{sin \\theta}")
        sec = TexMobject("sec \\theta = \\frac{1}{cos \\theta}")
        cot = TexMobject("cot \\theta = \\frac{1}{tan \\theta}")
        si.move_to(UP*2 + LEFT * 2)
        cosayn.move_to(LEFT*2)
        tan.move_to(LEFT * 2 + DOWN * 2)
        csc.move_to(UP*2+ RIGHT * 2)
        sec.move_to(RIGHT*2)
        cot.move_to (DOWN*2+ RIGHT * 2)
        
        self.play(Write(si),Write(cosayn), Write(tan), Write(csc), Write(sec), Write(cot))
        self.wait(10)
        self.play(FadeOut(si),FadeOut(cosayn), FadeOut(tan), FadeOut(csc), FadeOut(sec), FadeOut(cot))
        self.wait(5)

        grid = NumberPlane()
        self.add(grid)
        start = (0,0,0)
        end = (3,3,0)
        arc2 = Arc()
        arclabel = TexMobject("\\theta")
        arclabel.move_to(RIGHT* 0.2 + UP * 0.1)
        arclabel.scale(0.5)
        arc2.scale(0.22)
        arc2.move_to(RIGHT*0.3 + UP * 0.15)
        label1, label2, label3 = TextMobject("A"), TextMobject("B"), TextMobject("C")
        label1.move_to((3, 3.3, 0))
        label2.move_to((3, -0.3, 0))
        label3.move_to((0, -0.3, 0))
        theta_value = TexMobject("\\theta = 60 ^{\\circ}")
        theta_value.move_to((1,-1.5,0))
        sidelabel = TextMobject('hyp')
        sidelabel2 = TextMobject('height')
        sidelabel3 = TextMobject('50 m')
        sidelabel.move_to((1.5, 1.8, 0))
        sidelabel.rotate(PI/4)
        sidelabel2.move_to((3.6,1.5,0))
        sidelabel3.move_to((1.5,-0.5,0))
        
        line1 = Line(start, end)
        line2 = Line(end, (3,0,0))
        start2 = (3,0.5,0)
        end2 = (2.5,0.5,0)
        end3 = (2.5,0,0)
        line3 = Line(start2, end2)
        line4 = Line(end2, end3)
        self.play(ShowCreation(line1), ShowCreation(line2), ShowCreation(arc2), ShowCreation(arclabel), ShowCreation(line3), ShowCreation(line4))
        self.add(label1, label2, label3, sidelabel, sidelabel2, sidelabel3, theta_value)
        self.wait(10)
        
        self.remove(label1, label2, label3, sidelabel, sidelabel2, sidelabel3, theta_value)
        self.play(FadeOut(line1), FadeOut(line2), FadeOut(arc2), FadeOut(arclabel), FadeOut(line3), FadeOut(line4))
        self.remove(grid)
        self.wait(3)

        ans = TexMobject("tan 60 = \\frac{height}{50}")
        ans2 = TextMobject("height = 50 tan 60 meters!")

        self.play(Write(ans))
        self.wait(2)
        ans2.move_to(DOWN * 2)
        self.play(Write(ans2))
        self.wait(2)
        self.play(FadeOut(ans),FadeOut(ans2))

        '''insert unit circle diagram'''
        
        
